export const DogBreeds = () => {
  const breeds = [
    "Affenpinscher",
    "Afghan Hound",
    "African Hunting Dog",
    "Airedale Terrie",
    "Akbash",
    "Akita",
    "Alapaha Blue Blood Bulldog",
    "Alaskan Husky",
    "Alaskan Malamute",
    "American Bulldog",
    "American Eskimo",
    "American Foxhound",
    "American Pit bull Terrier",
    "American Stafordshire Terrier",
    "American Water Spaniel",
    "Anatolian Sheperd",
    "Appenzeller Sennenhund",
    "Australian Cattle Dog",
    "Australian Kelpie",
    "Australian Sheperd",
    "Australian Terrier",
    "Azawakh",
    "Barbet",
    "Basenji",
    "Basset Bleu de Gascogne",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Beauceron",
    "Bedlington Terrier",
    "Belgian Malinois",
    "Belgian Tervuren",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Black and Tan Coonhound",
    "Bloodhound",
    "Bluetick Coonhound",
    "Boerboel",
    "Border Collie",
    "Border Terrier",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Braco Italiano",
    "Briard",
    "Brittany",
    "Bull Terrier",
    "Miniature Bull Terrier",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corse",
    "Cardigan Welsh Corgi",
    "Catahoula Leopard Dog",
    "Caucasian Sheperd",
    "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever",
    "Chinese Crested",
    "Chinese Shar-Pei",
    "Chinook",
    "Chow Chow",
    "Clumber Spaniel",
    "Cocker Spaniel",
    "Colton de Tulear",
    "Dalmation",
    "Dogo Argentino",
    "Dutch Sheperd",
    "English Setter",
    "English Sheperd",
    "English Springer Spaniel",
    "English Toy Spaniel",
    "English Toy Terrier",
    "Eurasier",
    "Field Spaniel",
    "Finnish Lapphund",
    "Finnish Spitz",
    "French Bulldog",
    "German Pinscher",
    "German Sheperd",
    "German Shorthaired Pointer",
    "Giant Schnauzer",
    "Glen of Imaal Terrier",
    "Golden Retriever",
    "Gordon Setter",
    "Great Dane",
    "Great Pyrenees",
    "Greyhound",
    "Griffon Bruxellois",
    "Harrier",
    "Havanese",
    "Irish Setter",
    "Irish Terrier",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Japanese Chin",
    "Japanese Spit",
    "Keeshond",
    "Komondor",
    "Kooikerhondje",
    "Kuvasz",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Lancashire Heeler",
    "Leonberger",
    "Lhasa Apso",
    "Maltese",
    "Miniature American Sheperd",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Newfoundland",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog",
    "Olde English Bulldog",
    "Papillon",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Perro de Presa Canario",
    "Pharaoh Hound",
    "Plott",
    "Pomeranian",
    "Poodle (Miniature)",
    "Poodle (Toy)",
    "Pug",
    "Puli",
    "Pumi",
    "Rat Terrier",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Russian Toy",
    "Saint Bernard",
    "Saluki",
    "Samoyed",
    "Schipperke",
    "Schnauzer",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Shiloh Sheperd",
    "Siberian Husky",
    "Silky Terrier",
    "Smooth Fox Terrier",
    "Soft Coated Wheaten Terrier",
    "Spanish Water Dog",
    "Spinone Italiano",
    "Staffordshire Bull Terrier",
    "Swedish Vallhund",
    "Thai Ridgeback",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Toy Fox Terrier",
    "Treeing Walker Coonhound",
    "Vizsla",
    "Weimaraner",
    "Welsh Springer Spaniel",
    "West Highland White Terrier"
  ]
  return breeds
}